// <auto-generated />
using System;
using EmployeeManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710105037_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Engineering",
                            Designation = "Senior Software Engineer",
                            Email = "ava.thompson@example.com",
                            IsActive = true,
                            JoiningDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ava Thompson",
                            Salary = 95000m
                        },
                        new
                        {
                            Id = 2,
                            Department = "Human Resources",
                            Designation = "HR Manager",
                            Email = "liam.carter@example.com",
                            IsActive = true,
                            JoiningDate = new DateTime(2019, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Liam Carter",
                            Salary = 72000m
                        },
                        new
                        {
                            Id = 3,
                            Department = "Finance",
                            Designation = "Financial Analyst",
                            Email = "sophia.nguyen@example.com",
                            IsActive = true,
                            JoiningDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sophia Nguyen",
                            Salary = 68000m
                        },
                        new
                        {
                            Id = 4,
                            Department = "Engineering",
                            Designation = "DevOps Engineer",
                            Email = "noah.patel@example.com",
                            IsActive = true,
                            JoiningDate = new DateTime(2020, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Noah Patel",
                            Salary = 88000m
                        },
                        new
                        {
                            Id = 5,
                            Department = "Marketing",
                            Designation = "Marketing Specialist",
                            Email = "isabella.garcia@example.com",
                            IsActive = false,
                            JoiningDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Isabella Garcia",
                            Salary = 60000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
